import React from 'react'
import Head from 'next/head'
import Navbar from '../comps/Navbar/Navbar'
import Footer from '../comps/Footer/Footer'

export default function Layout(props) {
    return (
        <div >
             <Head>
                <title>1Pharmily</title>
                <meta name="description" content="Generated by create next app" />
                <link rel="icon" href="/logo.jpg" />
            </Head> 
            <Navbar/>
            {props.children}    
            <Footer/>
        </div>
    )
}
